vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.number = true
vim.o.mouse = "a"
vim.o.cursorline = true
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.expandtab = true
vim.o.termguicolors = true
vim.o.ic = true
vim.o.foldmethod='indent'
